version: '3'

services: 
  elastic:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.3'
    volumes: 
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.2.3'
    environment: 
      ELASTICSEARCH_URL: http://localhost:9200
    ports:
      - 5601:5601
    depends_on: 
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.3
    environment: 
      XPACK_MONITORING_ELASTICSEARCH_URL: http://localhost:9200
    volumes: 
      - /home/koudjo/sources/elk:/usr/share/logstash/pipeline/
    depends_on: 
      - elastic

volumes: 
  esdata:
    driver: local
